# -*- coding: utf-8 -*-

SettingsMAT = {
        "fus_dxv": "fusObjPort;FusObj_st;dxv_sw",
        "fus_dyv": "fusObjPort;FusObj_st;dyv_sw",
        "fus_wExistProb": "fusObjPort;FusObj_st;wExistProb_uw",
        "FR_dxN": "RObjFCSensor;m_movObjectInformation;m_dxN",
        "FR_dyN": "RObjFCSensor;m_movObjectInformation;m_dyN",
        "FR_Meas": "RObjFCSensor;m_movObjectInformation;m_Meas",
        "FV_dxN": "VObjFCSensor;m_objInformation;m_dxN",
        "FV_dyN": "VObjFCSensor;m_objInformation;m_dyN",
        "FV_Meas": "VObjFCSensor;m_objInformation;m_Meas",
        "LM_course_a0polynomCoef": "course_st;a0polynomCoef_sw",
        "LM_course_a1polynomCoef": "course_st;a1polynomCoef_sw",
        "LM_course_a2polynomCoef": "course_st;a2polynomCoef_sw",
        "LM_course_qModelConformity": "course_st;qCourseConformity_ub",
        "LM_course_dLeftBorder": "course_st;dLeftBorder_sw",
        "LM_course_dRightBorder": "course_st;dRightBorder_sw",
        "LM_dLowerLimitLane": "dLowerLimitLane_sw",
        "LM_dUpperLimitLane": "dUpperLimitLane_sw",
        "LM_lanes_dLeftBorder": [
            "lanes_st_0;dLeftBorder_sw",
            "lanes_st_1;dLeftBorder_sw",
            "lanes_st_2;dLeftBorder_sw",
        ],
        "LM_lanes_dRightBorder": [
            "lanes_st_0;dRightBorder_sw",
            "lanes_st_1;dRightBorder_sw",
            "lanes_st_2;dRightBorder_sw",
        ],
        "dLowerLimit": "ParallelLanesLmfAndOlr;dLowerLimit_sw",
        "dUpperLimit": "ParallelLanesLmfAndOlr;dUpperLimit_sw",
        "vidLine_handle": [
            "ensVLanesPort;eniVideoData;vidLine_st_0;handle_ub",
            "ensVLanesPort;eniVideoData;vidLine_st_1;handle_ub",
            "ensVLanesPort;eniVideoData;vidLine_st_2;handle_ub",
            "ensVLanesPort;eniVideoData;vidLine_st_3;handle_ub",
        ],
        "vidLine_dDxStart": [
            "ensVLanesPort;eniVideoData;vidLine_st_0;vidLineSegment_st;dDxStart_sw",
            "ensVLanesPort;eniVideoData;vidLine_st_1;vidLineSegment_st;dDxStart_sw",
            "ensVLanesPort;eniVideoData;vidLine_st_2;vidLineSegment_st;dDxStart_sw",
            "ensVLanesPort;eniVideoData;vidLine_st_3;vidLineSegment_st;dDxStart_sw",
        ],
        "vidLine_dDxEnd": [
            "ensVLanesPort;eniVideoData;vidLine_st_0;vidLineSegment_st;dDxEnd_sw",
            "ensVLanesPort;eniVideoData;vidLine_st_1;vidLineSegment_st;dDxEnd_sw",
            "ensVLanesPort;eniVideoData;vidLine_st_2;vidLineSegment_st;dDxEnd_sw",
            "ensVLanesPort;eniVideoData;vidLine_st_3;vidLineSegment_st;dDxEnd_sw",
        ],
        "vidLine_dDy": [
            "ensVLanesPort;eniVideoData;vidLine_st_0;vidLineSegment_st;dDy_sw",
            "ensVLanesPort;eniVideoData;vidLine_st_1;vidLineSegment_st;dDy_sw",
            "ensVLanesPort;eniVideoData;vidLine_st_2;vidLineSegment_st;dDy_sw",
            "ensVLanesPort;eniVideoData;vidLine_st_3;vidLineSegment_st;dDy_sw",
        ],
        "vidLine_wExistProb": [
            "ensVLanesPort;eniVideoData;vidLine_st_0;vidLineSegment_st;wExistProb_uw",
            "ensVLanesPort;eniVideoData;vidLine_st_1;vidLineSegment_st;wExistProb_uw",
            "ensVLanesPort;eniVideoData;vidLine_st_2;vidLineSegment_st;wExistProb_uw",
            "ensVLanesPort;eniVideoData;vidLine_st_3;vidLineSegment_st;wExistProb_uw",
        ],
        "vidLine_alpPsi": [
            "ensVLanesPort;eniVideoData;vidLine_st_0;vidLineSegment_st;alpPsi_sw",
            "ensVLanesPort;eniVideoData;vidLine_st_1;vidLineSegment_st;alpPsi_sw",
            "ensVLanesPort;eniVideoData;vidLine_st_2;vidLineSegment_st;alpPsi_sw",
            "ensVLanesPort;eniVideoData;vidLine_st_3;vidLineSegment_st;alpPsi_sw",
        ],
        "vidLine_kapHor": [
            "ensVLanesPort;eniVideoData;vidLine_st_0;vidLineSegment_st;kapHor_sw",
            "ensVLanesPort;eniVideoData;vidLine_st_1;vidLineSegment_st;kapHor_sw",
            "ensVLanesPort;eniVideoData;vidLine_st_2;vidLineSegment_st;kapHor_sw",
            "ensVLanesPort;eniVideoData;vidLine_st_3;vidLineSegment_st;kapHor_sw",
        ],
        "vidLine_kapDtHor": [
            "ensVLanesPort;eniVideoData;vidLine_st_0;vidLineSegment_st;kapDtHor_sw",
            "ensVLanesPort;eniVideoData;vidLine_st_1;vidLineSegment_st;kapDtHor_sw",
            "ensVLanesPort;eniVideoData;vidLine_st_2;vidLineSegment_st;kapDtHor_sw",
            "ensVLanesPort;eniVideoData;vidLine_st_3;vidLineSegment_st;kapDtHor_sw",
        ],
        "corridor_blue_right_dx": "corridor;staticBlueBorders;pointsRight;dx",
        "corridor_blue_right_dy": "corridor;staticBlueBorders;pointsRight;dy",
        "corridor_blue_left_dx": "corridor;staticBlueBorders;pointsLeft;dx",
        "corridor_blue_left_dy": "corridor;staticBlueBorders;pointsLeft;dy",
        "corridor_blue_right_dx_next_rot": "corridor;staticBlueBorders;pointsRight;dx_next_rot",
        "corridor_blue_right_dy_next_rot": "corridor;staticBlueBorders;pointsRight;dy_next_rot",
        "corridor_blue_left_dx_next_rot": "corridor;staticBlueBorders;pointsLeft;dx_next_rot",
        "corridor_blue_left_dy_next_rot": "corridor;staticBlueBorders;pointsLeft;dy_next_rot",
    }
